In [11]:
import pandas as pd
df = pd.read_csv('usarrests.csv')
df.shape

(50, 4)

In [12]:
df.head(10)

    Unnamed: 0  Murder  Assault  UrbanPop
0      Alabama    13.2    236.0        58
1       Alaska    10.0    263.0        48
2      Arizona     8.1    294.0        80
3     Arkansas     8.8    190.0        50
4   California     9.0    276.0        91
5     Colorado     7.9    204.0        78
6  Connecticut     3.3    110.0        77
7     Delaware     5.9    238.0        72
8      Florida    15.4    335.0        80
9      Georgia    17.4      NaN        60

In [13]:
df.dtypes

Unnamed: 0     object
Murder        float64
Assault       float64
UrbanPop        int64
dtype: object

In [14]:
df.describe()

         Murder     Assault   UrbanPop
count  50.00000   49.000000   50.00000
mean    7.78800  182.183673   74.20000
std     4.35551  130.877435   73.40828
min     0.80000   45.000000    6.00000
25%     4.07500  109.000000   53.25000
50%     7.25000  159.000000   66.00000
75%    11.25000  249.000000   77.75000
max    17.40000  879.000000  570.00000

checking for missing values

In [15]:
df.isna().sum()

Unnamed: 0    0
Murder        0
Assault       1
UrbanPop      0
dtype: int64

In [16]:
fill_value = df['Assault'].mean()
df['Assault'] = df['Assault'].fillna(fill_value)
print(fill_value)

182.18367346938774

filtering by suspicious values

In [17]:
print(df.duplicated().sum())

0

In [18]:
df[df['UrbanPop'] > 100]

   Unnamed: 0  Murder  Assault  UrbanPop
14       Iowa     2.2     56.0       570

In [19]:
df[df['Assault'] > 300]

        Unnamed: 0  Murder  Assault  UrbanPop
8          Florida    15.4    335.0        80
32  North Carolina    13.0    337.0        45
39  South Carolina    14.4    879.0        48

There were 3 suspicious values I noticed in the data
1. Georgia was missing a value for assualts, which should not be possible. I replaced the missing value with the mean.
2. The urban population of Iowa is over 100%. Seeing as the murder and assault rates are below average, it should be impossible for Iowa to have the highest urban population. I would not delete the row, because the data is needed, but I would go back and see how the data was collected. SPecifically, I would look for duplicated or improper calculations.
3. Another strange value I noteced was that South Carolina had the highest assault rates, but lower population and murder rates. While this isn't impossible, the values do seem to be very extreme and I would go back to see how the data was collected for this as well.