In [32]:
import pandas as pd
df = pd.read_csv('titanic_train.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [33]:
import sklearn
from sklearn.model_selection import train_test_split
X = df[["Pclass"]]
y = df[["Survived"]]
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42)
print('X_train:', X_train, 'X_test:', X_test, 'y_train:', y_train, 'y_test:', y_test)

X_train:      Pclass
445       1
650       3
172       3
450       2
314       2
..      ...
106       3
270       1
860       3
435       1
102       1

[623 rows x 1 columns] X_test:      Pclass
709       3
439       2
840       3
720       2
39        3
..      ...
821       3
633       1
456       1
500       3
430       1

[268 rows x 1 columns] y_train:      Survived
445         1
650         0
172         1
450         0
314         0
..        ...
106         1
270         0
860         0
435         1
102         0

[623 rows x 1 columns] y_test:      Survived
709         1
439         0
840         0
720         1
39          1
..        ...
821         1
633         0
456         0
500         0
430         1

[268 rows x 1 columns]

In [34]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)

In [35]:
knn.fit(X_train, y_train)
print(knn.score(X_test, y_test))

0.6940298507462687

/usr/local/lib/python3.13/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

Based on the KNN Classifier, the model would get the surviving passengers correct only 69% of the time.

In [36]:
import pandas as pd
df2 = pd.read_csv('titanic_test.csv')
df2.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [37]:
df2.shape

(418, 11)

In [38]:
df2.dtypes

PassengerId      int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [39]:
df2.isna().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [40]:
fill_value = df2['Age'].median()
df2['Age'] = df2['Age'].fillna(fill_value)
print(fill_value)

27.0

In [41]:
df2.isna().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [46]:
X = df2[["Pclass"]]
y = df2[["Age"]]
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42)
print('X_train:', X_train, 'X_test:', X_test, 'y_train:', y_train, 'y_test:', y_test)

X_train:      Pclass
118       1
271       3
114       1
311       3
131       1
..      ...
71        3
106       3
270       1
348       2
102       3

[292 rows x 1 columns] X_test:      Pclass
321       3
324       1
388       3
56        3
153       3
..      ...
101       2
310       3
29        3
195       3
390       1

[126 rows x 1 columns] y_train:       Age
118  36.0
271  27.0
114  63.0
311  22.0
131  53.0
..    ...
71   21.0
106  21.0
270  46.0
348  24.0
102  27.0

[292 rows x 1 columns] y_test:       Age
321  25.0
324  39.0
388  21.0
56   35.0
153  36.0
..    ...
101  27.0
310  18.0
29   27.0
195  33.0
390  23.0

[126 rows x 1 columns]